language: objective-c
osx_image: xcode8.3
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script:
- "./build.sh PromiseKit/Photos PMKPhotos"
deploy:
  provider: releases
  api_key:
    secure: Q0Evu6c/uLPQJM2oC2SEy4Wdqp9b5oHvMeBZBp2/+hVINPQbdInMQyUSvMNqECVcOYe301rBNw0NFw8dESevwY1cOO7iPBhPT0knGKS4wf3WsMP2f2A8lXidNLLIQz53pbfmdmUmYlzLhDDgKXKgOHgDUV04WWGj0KU/hF5n4Pko4IR3z4FSnhUyT94c0CuoPxN6eiKOUR2VWyU6nkFXI776ldJukQHcyZADivsQbaHDejCd1pKP8ErgNyQXppszNtI+cVmaK/P+nev0jPMWzsaTCZvhFw7dGgYZ9P0LPb9xz8n1UNoJQMusiUiSPKRtq0Q4F+LcJNKKReMiMuq0uXhwdy9QJ4fU3jLxfp9/+0fHJgX5XBCSqz//IO3D/tTEac2XRjmA/Z0XyA70FZ050s2FilLdaI5cc+hpHafoT2F9SjvIPgD/Egxw9KTh0SYZp9hN4YRGiX4dbMlV4BPLusvgPOZpBTNBEMrKvhQMagc3G83gwG4oq7lZEr03xOubQKhr41HzBg2ibA7TBKK+gIYg0PGLsg6w1+pTW7zbk+I8SC1RdjjZ4+eAjkjiL5sIr7Kc3ekO9KZ5utBOWBP4qu/DNKvFBFlp4bVWwl+6T5ManoeLZd5oCr9X/fVZ+ffIJNC+PJJLltnG4l6T8Kb30OF3eo+snI5x6w6YrMHvx1A=
  file_glob: true
  file: Archives/*
  skip_cleanup: true
  on:
    tags: true
